;
; Copyright (c) 2016 Mieszko Mazurek
;

OFF_NEXT	= 0x0
OFF_PREV	= 0x2
OFF_SPTR	= 0x4
OFF_SPND	= 0x6
OFF_FLAG	= 0x8
OFF_PDNG	= 0x9
OFF_NAME	= 0xA

CTX_SIZE	= 35
THR_SIZE	= 12
STC_MARGIN	= 15

OFF_NEXTL	= OFF_NEXT
OFF_NEXTH	= OFF_NEXT+1
OFF_PREVL	= OFF_PREV
OFF_PREVH	= OFF_PREV+1
OFF_SPTRL	= OFF_SPTR
OFF_SPTRH	= OFF_SPTR+1
OFF_SPNDL	= OFF_SPND
OFF_SPNDH	= OFF_SPND+1
OFF_NAMEL	= OFF_NAME
OFF_NAMEH	= OFF_NAME+1

FLAG_FREE	= 0x01
